from flask import Flask, render_template, request, jsonify
from chatterbot import ChatBot
from chatterbot.trainers import ChatterBotCorpusTrainer
import re  # Add this import at the top of app.py


def sanitise_input(message):
    """
    Clean and validate user input.
    Returns cleaned message or None if invalid.
    """
    if not message:
        return None

    # Remove leading/trailing whitespace
    message = message.strip()

    # Check if message is empty after stripping
    if not message:
        return None

    # Remove HTML tags (prevents script injection)
    message = re.sub(r"<[^>]+>", "", message)

    # Check length after cleaning
    if len(message) > 500:
        return None

    return message


# Create the Flask application
app = Flask(__name__)

# Initialize the chatbot
chatbot = ChatBot(
    "GlebBot",
    storage_adapter="chatterbot.storage.SQLStorageAdapter",
    database_uri="sqlite:///chatbot_database.sqlite3",
)

# Train the chatbot with English conversations
trainer = ChatterBotCorpusTrainer(chatbot)
trainer.train("chatterbot.corpus.english")

from chatterbot.trainers import ListTrainer

list_trainer = ListTrainer(chatbot)

# Train on school-related conversations
list_trainer.train(
    [
        "What subjects do you like?",
        "As an AI bot I do not have opinions" "Can you help with homework?",
        "I can try to help explain concepts, but you should do your own work!",
        "Who made you?",
        "I was created by a talented Year 9 student at Tempe High School!",
        "what is one plus one?",
        "Two",
        "what is 1 + 1",
        "Two",
        "what is your name?",
        "My name is Gleb AI, here to help!",
    ]
)

# Train on greetings
list_trainer.train(
    [
        "Good morning!",
        "Good morning! How can I help you today?",
        "Good afternoon!",
        "Good afternoon! What would you like to chat about?",
    ]
)

# Train on math
list_trainer.train(
    [
        "What is 2 + 2",
        "Four",
        "what is Two plus Two",
        "Four",
        "what is 2 times 2",
        "Four",
        "What is 8 times 8?",
        "64",
        "whats 3+5",
        "that would be 8",
        "what is 10 plus ten",
        "its 20",
        "what is 10 + 10",
        "20",
    ]
)

# Train on more math
list_trainer.train(
    [
        "What is 1 + 1",
        "2",
        "What is 2 + 3",
        "5",
        "what is 4 + 9",
        "13",
        "what is 10 minus 7",
        "3",
        "what is 15 minus 5",
        "10",
        "what is 20 minus 13",
        "7",
        "what is 3 times 4",
        "12",
        "what is 5 times 9",
        "45",
        "what is 7 times 6",
        "42",
        "What is 8 times 12?",
        "96",
        "what is 9 times 11",
        "99",
        "what is 12 times 12",
        "144",
        "what is 100 divided by 10",
        "10",
        "What is 81 divided by 9?",
        "9",
        "what is 64 divided by 8",
        "8",
        "whats 14+16",
        "that would be 30",
        "whats 25+75",
        "100",
        "what is 200 minus 150",
        "50",
        "what is 300 minus 125",
        "175",
        "what is 2 squared",
        "4",
        "what is 3 squared",
        "9",
        "what is 4 squared",
        "16",
        "what is 5 squared",
        "25",
        "what is 10 squared",
        "100",
        "what is 2 cubed",
        "8",
        "what is 3 cubed",
        "27",
        "what is 4 cubed",
        "64",
        "what is 2 to the power of 6",
        "64",
        "what is 3 to the power of 4",
        "81",
        "what is 5 to the power of 3",
        "125",
        "what is 1/2 + 1/2",
        "1",
        "what is 3/4 + 1/4",
        "1",
        "what is 5/6 minus 1/6",
        "4/6",
        "what is 7/8 minus 3/8",
        "4/8",
        "what is 9 + 18",
        "27",
        "what is 45 + 55",
        "100",
        "what is 99 minus 44",
        "55",
        "what is 123 minus 23",
        "100",
        "what is 11 times 11",
        "121",
        "what is 13 times 7",
        "91",
        "what is 14 times 5",
        "70",
        "what is 16 times 4",
        "64",
        "what is 18 divided by 3",
        "6",
        "what is 49 divided by 7",
        "7",
        "what is 121 divided by 11",
        "11",
        "whats 6+17",
        "23",
        "whats 8+19",
        "27",
        "whats 33+67",
        "100",
        "what is 500 minus 250",
        "250",
        "what is 1000 minus 1",
        "999",
        "what is 9 times 12",
        "108",
        "what is 15 times 15",
        "225",
        "what is 20 times 20",
        "400",
        "what is 144 divided by 12",
        "12",
        "what is 225 divided by 15",
        "15",
        "what is 400 divided by 20",
        "20",
        "what is 30 + 45",
        "75",
        "what is 60 + 90",
        "150",
        "what is 100 + 250",
        "350",
        "what is 75 minus 25",
        "50",
        "what is 80 minus 30",
        "50",
        "what is 90 minus 45",
        "45",
        "what is 21 times 2",
        "42",
        "what is 22 times 3",
        "66",
        "what is 24 times 5",
        "120",
        "what is 36 divided by 6",
        "6",
        "what is 72 divided by 8",
        "9",
        "what is 90 divided by 9",
        "10",
        "what is 7 plus 14",
        "21",
        "what is 8 plus 24",
        "32",
        "what is 9 plus 36",
        "45",
        "What is 46 + 27",
        "73",
        "what is 95 minus 48",
        "47",
        "what is 23 times 12",
        "276",
        "What is 360 divided by 12?",
        "30",
        "what is 111 plus 222",
        "333",
        "what is 500 minus 123",
        "377",
        "what is 19 times 18",
        "342",
        "what is 625 divided by 25",
        "25",
        "what is 2.4 + 3.6",
        "6",
        "what is 10.5 minus 4.5",
        "6",
        "what is 2.5 times 8",
        "20",
        "What is 15 divided by 0.5?",
        "30",
        "what is 4 to the power of 4",
        "256",
        "what is 7 to the power of 3",
        "343",
        "what is the square root of 144",
        "12",
        "what is the square root of 225",
        "15",
        "what is 6/7 + 1/7",
        "1",
        "what is 9/12 minus 3/12",
        "6/12",
        "what is 12 percent of 50",
        "6",
        "what is 40 percent of 90",
        "36",
        "what is 8 factorial",
        "40320",
        "what is 10 factorial",
        "3628800",
        "what is 14 times 16",
        "224",
        "what is 27 times 11",
        "297",
        "what is 121 divided by 11",
        "11",
        "what is 144 divided by 9",
        "16",
        "what is 3 squared plus 5 squared",
        "34",
        "what is 10 cubed",
        "1000",
        "what is 1.25 + 0.75",
        "2",
        "what is 5.5 minus 2.2",
        "3.3",
        "what is 9 times 15",
        "135",
        "what is 250 minus 175",
        "75",
        "what is 48 divided by 6",
        "8",
        "what is 18 plus 27 minus 5",
        "40",
        "what is (9 + 6) times 4",
        "60",
        "what is 200 divided by 5 plus 10",
        "50",
        "what is 7 times 8 minus 6",
        "50",
        "what is 100 minus (20 + 30)",
        "50",
        "what is 13 times 13",
        "169",
        "what is 17 squared",
        "289",
        "what is 2/5 + 2/5",
        "4/5",
        "what is 11/20 minus 1/20",
        "10/20",
        "what is 75 percent of 200",
        "150",
        "what is 5 percent of 300",
        "15",
        "what is 64 plus 128",
        "192",
        "what is 512 divided by 8",
        "64",
        "what is 90 minus 45 plus 5",
        "50",
        "what is (3 + 7) squared",
        "100",
        "What is 37 + 58",
        "95",
        "what is 84 minus 29",
        "55",
        "what is 13 times 17",
        "221",
        "What is 144 divided by 16?",
        "9",
        "what is 19 plus 26",
        "45",
        "what is 72 minus 38",
        "34",
        "what is 21 times 14",
        "294",
        "what is 225 divided by 25",
        "9",
        "what is 0 plus 99",
        "99",
        "what is 1000 minus 875",
        "125",
        "what is 18 times 13",
        "234",
        "What is 196 divided by 14?",
        "14",
        "what is 27 plus 73",
        "100",
        "what is 88 minus 44",
        "44",
        "what is 32 times 15",
        "480",
        "what is 256 divided by 32",
        "8",
        "what is 45 plus 67",
        "112",
        "what is 123 minus 57",
        "66",
        "what is 14 times 14",
        "196",
        "what is 169 divided by 13",
        "13",
        "what is 5 factorial",
        "120",
        "what is the square root of 81",
        "9",
        "what is the square root of 121",
        "11",
        "what is 2/3 + 1/3",
        "1",
        "what is 5/8 + 1/8",
        "6/8",
        "what is 9/10 minus 4/10",
        "5/10",
        "what is 3.5 + 2.5",
        "6",
        "what is 7.2 minus 1.2",
        "6",
        "what is 1.5 times 4",
        "6",
        "what is 12 divided by 0.5",
        "24",
        "what is 2 to the power of 8",
        "256",
        "what is 10 percent of 200",
        "20",
        "what is 25 percent of 80",
        "20",
        "what is 3 squared plus 4 squared",
        "25",
        "what is 6 cubed",
        "216",
        "what is 11 times 13",
        "143",
        "what is 17 times 19",
        "323",
        "what is 100 divided by 4",
        "25",
        "what is 999 minus 333",
        "666",
        "what is 48 plus 52",
        "100",
        "what is 64 minus 16",
        "48",
        "what is 7 times 9",
        "63",
        "what is 81 divided by 3",
        "27",
        "what is 4 squared minus 5",
        "11",
        "what is 20 plus 30 minus 10",
        "40",
        "what is 9 times 5 plus 5",
        "50",
        "what is 100 minus 20 times 2",
        "60",
        "what is (8 + 2) times 5",
        "50",
        "what is 144 divided by 12 plus 3",
        "15",
        "What is 58 + 76",
        "134",
        "what is 902 minus 457",
        "445",
        "what is 34 times 21",
        "714",
        "What is 420 divided by 7?",
        "60",
        "what is 1.2 + 3.8",
        "5",
        "what is 9.9 minus 4.4",
        "5.5",
        "what is 6.25 times 4",
        "25",
        "What is 18 divided by 0.25?",
        "72",
        "what is 5 to the power of 4",
        "625",
        "what is 9 to the power of 3",
        "729",
        "what is the square root of 169",
        "13",
        "what is the square root of 256",
        "16",
        "what is 4/9 + 2/9",
        "6/9",
        "what is 7/10 minus 2/10",
        "5/10",
        "what is 15 percent of 60",
        "9",
        "what is 35 percent of 200",
        "70",
        "what is 9 factorial",
        "362880",
        "what is 3 cubed plus 2",
        "29",
        "what is 8 squared minus 10",
        "54",
        "what is 45 times 12",
        "540",
        "what is 360 divided by 15",
        "24",
        "what is 2.75 + 1.25",
        "4",
        "what is 14.4 minus 4.4",
        "10",
        "what is 125 divided by 0.5",
        "250",
        "what is 6 times 14 minus 4",
        "80",
        "what is (12 + 8) times 3",
        "60",
        "what is 300 divided by 6 plus 20",
        "70",
        "what is 100 minus 25 times 2",
        "50",
        "what is 11 times 14",
        "154",
        "what is 16 squared",
        "256",
        "what is 18 squared",
        "324",
        "what is 2/3 + 2/6",
        "1",
        "what is 13/15 minus 3/15",
        "10/15",
        "what is 60 percent of 150",
        "90",
        "what is 2 percent of 500",
        "10",
        "what is 77 plus 88",
        "165",
        "what is 1001 minus 999",
        "2",
        "what is 72 times 5",
        "360",
        "what is 640 divided by 16",
        "40",
        "what is 5 squared plus 6 squared",
        "61",
        "what is (4 + 6) squared",
        "100",
        "what is 81 divided by 0.9",
        "90",
        "what is 7.5 times 2",
        "15",
        "what is 0.8 plus 0.2",
        "1",
        "what is 50 minus (15 + 10)",
        "25",
        "what is 22 times 22",
        "484",
        "what is 144 plus 256",
        "400",
        "what is 10000 minus 1",
        "9999",
        "what is 27 times 4 minus 8",
        "100",
        "What is 0 + 0",
        "0",
        "what is 1 + 0",
        "1",
        "what is 1 + 1",
        "2",
        "what is 2 + 0",
        "2",
        "what is 2 + 1",
        "3",
        "what is 2 + 2",
        "4",
        "what is 3 + 0",
        "3",
        "what is 3 + 1",
        "4",
        "what is 3 + 2",
        "5",
        "what is 3 + 3",
        "6",
        "what is 4 + 0",
        "4",
        "what is 4 + 1",
        "5",
        "what is 4 + 2",
        "6",
        "what is 4 + 3",
        "7",
        "what is 4 + 4",
        "8",
        "what is 5 + 0",
        "5",
        "what is 5 + 1",
        "6",
        "what is 5 + 2",
        "7",
        "what is 5 + 3",
        "8",
        "what is 5 + 4",
        "9",
        "what is 5 + 5",
        "10",
        "what is 6 + 0",
        "6",
        "what is 6 + 1",
        "7",
        "what is 6 + 2",
        "8",
        "what is 6 + 3",
        "9",
        "what is 6 + 4",
        "10",
        "what is 7 + 0",
        "7",
        "what is 7 + 1",
        "8",
        "what is 7 + 2",
        "9",
        "what is 7 + 3",
        "10",
        "what is 8 + 0",
        "8",
        "what is 8 + 1",
        "9",
        "what is 8 + 2",
        "10",
        "what is 9 + 0",
        "9",
        "what is 9 + 1",
        "10",
        "what is 10 + 0",
        "10",
        "What is 1 + 10",
        "11",
        "what is 2 + 9",
        "11",
        "what is 3 + 8",
        "11",
        "what is 4 + 7",
        "11",
        "what is 5 + 6",
        "11",
        "what is 2 + 10",
        "12",
        "what is 3 + 9",
        "12",
        "what is 4 + 8",
        "12",
        "what is 5 + 7",
        "12",
        "what is 6 + 6",
        "12",
        "what is 3 + 10",
        "13",
        "what is 4 + 9",
        "13",
        "what is 5 + 8",
        "13",
        "what is 6 + 7",
        "13",
        "what is 4 + 10",
        "14",
        "what is 5 + 9",
        "14",
        "what is 6 + 8",
        "14",
        "what is 7 + 7",
        "14",
        "what is 5 + 10",
        "15",
        "what is 6 + 9",
        "15",
        "what is 7 + 8",
        "15",
        "what is 6 + 10",
        "16",
        "what is 7 + 9",
        "16",
        "what is 8 + 8",
        "16",
        "what is 7 + 10",
        "17",
        "what is 8 + 9",
        "17",
        "what is 8 + 10",
        "18",
        "what is 9 + 9",
        "18",
        "what is 9 + 10",
        "19",
        "what is 10 + 10",
        "20",
        "what is 11 + 0",
        "11",
        "what is 12 + 0",
        "12",
        "what is 13 + 0",
        "13",
        "what is 14 + 0",
        "14",
        "what is 15 + 0",
        "15",
        "what is 16 + 0",
        "16",
        "what is 17 + 0",
        "17",
        "what is 18 + 0",
        "18",
        "what is 19 + 0",
        "19",
        "what is 20 + 0",
        "20",
        "What is 11 + 10",
        "21",
        "what is 12 + 9",
        "21",
        "what is 13 + 8",
        "21",
        "what is 14 + 7",
        "21",
        "what is 15 + 6",
        "21",
        "what is 12 + 10",
        "22",
        "what is 13 + 9",
        "22",
        "what is 14 + 8",
        "22",
        "what is 15 + 7",
        "22",
        "what is 16 + 6",
        "22",
        "what is 13 + 10",
        "23",
        "what is 14 + 9",
        "23",
        "what is 15 + 8",
        "23",
        "what is 16 + 7",
        "23",
        "what is 17 + 6",
        "23",
        "what is 14 + 10",
        "24",
        "what is 15 + 9",
        "24",
        "what is 16 + 8",
        "24",
        "what is 17 + 7",
        "24",
        "what is 18 + 6",
        "24",
        "what is 15 + 10",
        "25",
        "what is 16 + 9",
        "25",
        "what is 17 + 8",
        "25",
        "what is 18 + 7",
        "25",
        "what is 19 + 6",
        "25",
        "what is 16 + 10",
        "26",
        "what is 17 + 9",
        "26",
        "what is 18 + 8",
        "26",
        "what is 19 + 7",
        "26",
        "what is 20 + 6",
        "26",
        "what is 17 + 10",
        "27",
        "what is 18 + 9",
        "27",
        "what is 19 + 8",
        "27",
        "what is 20 + 7",
        "27",
        "what is 18 + 10",
        "28",
        "what is 19 + 9",
        "28",
        "what is 20 + 8",
        "28",
        "what is 19 + 10",
        "29",
        "what is 20 + 9",
        "29",
        "what is 20 + 10",
        "30",
        "what is 21 + 9",
        "30",
        "what is 22 + 8",
        "30",
        "what is 23 + 7",
        "30",
        "what is 24 + 6",
        "30",
        "what is 25 + 5",
        "30",
        "what is 26 + 4",
        "30",
        "what is 27 + 3",
        "30",
        "what is 28 + 2",
        "30",
        "what is 29 + 1",
        "30",
        "what is 30 + 0",
        "30",
        "what is 20 + 20",
        "40",
        "what is 19 + 20",
        "39",
        "what is 18 + 20",
        "38",
        "what is 17 + 20",
        "37",
        "what is 16 + 20",
        "36",
        "what is 15 + 20",
        "35",
        "what is 14 + 20",
        "34",
        "what is 13 + 20",
        "33",
        "what is 12 + 20",
        "32",
        "what is 11 + 20",
        "31",
    ]
)

# Train on conversation
list_trainer.train(
    [
        "No",
        "Whats wrong?",
        "Just no",
        "can you tell me whats wrong?",
        "thats right!",
        "Thank you!",
    ]
)


@app.route("/")
def home():
    """Serve the main chat page."""
    return render_template("index.html")


CRISIS_KEYWORDS = [
    "suicide",
    "kill myself",
    "end my life",
    "self harm",
    "self-harm",
    "dont want to live",
    "don't want to live",
    "want to die",
    "I what to kill someone",
    "I what to kill",
    "I what to end it all",
    "Kill",
    "end it all",
    "Ima kill my self",
    "Kill my self",
    "I what to kill them",
    "I will kill myself",
    "I what to kill my self",
]

CRISIS_RESPONSE = """I'm concerned about what you've shared. Please know that you're not alone.

If you're in crisis, please reach out for support:

- Lifeline: 13 11 14 (24/7)
- Kids Helpline: 1800 55 1800
- Beyond Blue: 1300 22 4636

I'm just a chatbot and can't provide the support you need."""


def check_for_crisis(message):
    """Check if message contains crisis keywords."""
    message_lower = message.lower()
    for keyword in CRISIS_KEYWORDS:
        if keyword in message_lower:
            return True
    return False


@app.route("/chat", methods=["POST"])
def chat():
    """Handle chat messages and return bot responses."""
    data = request.get_json()
    raw_message = data.get("message", "")

    # Sanitise and validate input
    user_message = sanitise_input(raw_message)

    if user_message is None:
        if not raw_message or not raw_message.strip():
            return jsonify({"response": "Please enter a message!"})
        else:
            return jsonify(
                {"response": "Message too long! Please keep it under 500 characters."}
            )

    # Safety check for crisis keywords (use original for better detection)
    if check_for_crisis(raw_message):
        return jsonify({"response": CRISIS_RESPONSE})

    # Get the chatbot's response
    bot_response = chatbot.get_response(user_message)

    return jsonify({"response": str(bot_response)})


if __name__ == "__main__":
    app.run(host="0.0.0.0", port=5000, debug=True)
